name: Deploy Backend -> Contoso.WebApi 

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  AZURE_WEBAPP_FRONTEND: 'contoso-webapp'
  AZURE_WEBAPP_NAME: 'contoso-api'    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '3.1' 
  working-directory: ./src/Contoso.WebApi        # set this to the dot net version to use
  working-directory-frontend: ./src/Contoso.Web
  working-directory-functionapp: ./src/Contoso.FunctionApp
  ERROR_FLAG_WEBAPI: 'true'
  ERROR_FLAG_FUNCTIONAPP: 'true'
  AZURE_FUNCTIONAPP_NAME: 'contoso-function' # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'    # set this to the path to your web app project, defaults to the repository root

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      backendwebapi: ${{ steps.filter.outputs.backendwebapi }}
      backendfunctionapp: ${{ steps.filter.outputs.backendfunctionapp }}
    steps:
    - uses: actions/checkout@master
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          backendwebapi:
            - 'src/Contoso.WebApi/**'
          backendfunctionapp:
            - 'src/Contoso.FunctionApp/**'

  build-and-deploy-WebApi:
    needs: changes
    if: ${{ needs.changes.outputs.backendwebapi == 'true' }}
    runs-on: ubuntu-latest
    steps:

    # checkout the repo
    - uses: actions/checkout@master
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Setup__.net__core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }} 

    - name: Print working directory
      run: |
        pwd
      
    # Run dotnet build and publish
    - name: dotnet build and publish
      run: |
        dotnet restore
        dotnet build --configuration Release
        dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
      working-directory: ${{ env.working-directory }}
    
    #If success then deploy condition here
       
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
        package: '${{ env.working-directory }}'
    
    #If failure raise issue
  
    - name: logout
      run: |
        az logout

    - name: divide error
      run: exit 204

    - name: Checking ERRORS in job
      if: ${{ cancelled() }}
      uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_COMMIT_SHA: ${{ github.sha }}
        GITHUB_OWNER: 'BharatKJain'
        GITHUB_REPOSITORY: 'microsoft-github-hack'
        GITHUB_ISSUE_TITLE: 'Facing issue with Divide Error'
        GITHUB_ISSUE_BODY: 'Please check'

  # pull-request-creation:
  #   needs: build-and-deploy-WebApi
  #   steps:
  #   - name: Update npm packages
  #     uses: technote-space/create-pr-action@v2
  #     with:
  #       COMMIT_MESSAGE: 'chore: testing'
  #       COMMIT_NAME: 'GitHub Actions'
  #       COMMIT_EMAIL: 'bharat.mayoor77@gmail.com'
  #       PR_BRANCH_NAME: 'chore-update-${PR_ID}'
  #       PR_TITLE: 'chore: update dependencies'
  
  # issue-creation:
  #   needs: [build-and-deploy-function-app,build-and-deploy-WebApi]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@master
  #     - name: Checking The Function App Job
  #       if: ${{env.ERROR_FLAG_FUNCTIONAPP == 'true'}}
  #       uses: JasonEtco/create-an-issue@v2
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         GITHUB_COMMIT_SHA: ${{ github.sha }}
  #         GITHUB_OWNER: 'BharatKJain'
  #         GITHUB_REPOSITORY: 'microsoft-github-hack'
  #         GITHUB_ISSUE_TITLE: 'Facing issue with Divide Error'
  #         GITHUB_ISSUE_BODY: 'Please check'
  #     - name: Checking the Web Api Job
  #       if: ${{env.ERROR_FLAG_WEBAPI == 'true'}}
  #       uses: JasonEtco/create-an-issue@v2
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         GITHUB_COMMIT_SHA: ${{ github.sha }}
  #         GITHUB_OWNER: 'BharatKJain'
  #         GITHUB_REPOSITORY: 'microsoft-github-hack'
  #         GITHUB_ISSUE_TITLE: 'Facing issue with Divide Error'
  #         GITHUB_ISSUE_BODY: 'Please check'
    
# Issue Creation after failure
# IF succeeds -> Deploy