name: Deploy ASP.NET MVC App deploy to Azure Web App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  AZURE_WEBAPP_FRONTEND: 'contoso-webapp'
  AZURE_WEBAPP_NAME: 'contoso-api'    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '3.1' 
  working-directory: ./src/Contoso.WebApi        # set this to the dot net version to use
  working-directory-frontend: ./src/Contoso.Web
  working-directory-functionapp: ./src/Contoso.FunctionApp
  ERROR_FLAG: false
  AZURE_FUNCTIONAPP_NAME: 'contoso-function' # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'    # set this to the path to your web app project, defaults to the repository root

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          backend:
            - 'src/Contoso.WebApi/**'
          frontend:
            - 'src/Contoso.Web/**'
    - name: backend tests
      if: steps.filter.outputs.backend == 'true'
      run: |
        echo "Backend Has Changes"
    - name: frontend tests
      if: steps.filter.outputs.frontend == 'true'
      run: |
        echo "Frontend Has Changes"